POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "marcos",
  "sobrenome": "carlos",
  "email": "joao@gmail.com",
  "password": "123456",
  "confirmPassword": "123456"
}

###
GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/users/6446c2fa245fa01da548ed15
###

DELETE http://localhost:3000/api/users/6446c2fa245fa01da548ed15

###
PUT  http://localhost:3000/api/users/6446c664c3c3ba7bce70fc0f
Content-Type: application/json

{
  "name": "TESTE DE ATUALIÇÃO",
  "sobrenome": "carlos",
  "email": "joao@gmail.com",
  "password": "123456",
  "confirmPassword": "123456"
}

### token
GET http://localhost:3000/apiSpotify/token
### 
GET http://localhost:3000/apiSpotify/user